name: Advanced SSH & Web Terminal
version: 18.0.0
slug: ssh
description: A supercharged SSH & Web Terminal access to your Home Assistant instance
url: https://github.com/hassio-addons/addon-ssh
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 0
ingress_stream: true
init: false
panel_icon: mdi:console
panel_title: Terminal
homeassistant: 0.92.0b2
arch:
- aarch64
- amd64
- armv7
ports:
  22/tcp: 22
ports_description:
  22/tcp: SSH server port (make empty to disable)
hassio_api: true
hassio_role: manager
services:
- mysql:want
- mqtt:want
homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: true
apparmor: false
host_dbus: true
docker_api: true
privileged:
- NET_ADMIN
- SYS_ADMIN
- SYS_RAWIO
- SYS_TIME
- SYS_NICE
devices:
- /dev/mem
map:
- addons:rw
- all_addon_configs:rw
- backup:rw
- homeassistant_config:rw
- media:rw
- share:rw
- ssl:rw
journald: true
options:
  ssh:
    username: hassio
    password: ''
    authorized_keys: []
    sftp: false
    compatibility_mode: false
    allow_agent_forwarding: false
    allow_remote_port_forwarding: false
    allow_tcp_forwarding: false
  zsh: true
  share_sessions: false
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssh:
    username: str
    password: password
    authorized_keys:
    - str
    sftp: bool
    compatibility_mode: bool
    allow_agent_forwarding: bool
    allow_remote_port_forwarding: bool
    allow_tcp_forwarding: bool
  zsh: bool
  share_sessions: bool
  packages:
  - str
  init_commands:
  - str
image: ghcr.io/hassio-addons/ssh/{arch}
