arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Monitoring and tracking tool for Plex Media Server
hassio_api: true
image: ghcr.io/hassio-addons/tautulli/{arch}
init: false
map:
- share:rw
- backup:rw
name: Tautulli
ports:
  8181/tcp: 8181
ports_description:
  8181/tcp: Tautulli web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
slug: tautulli
url: https://github.com/hassio-addons/addon-tautulli/tree/main/README.md
version: 3.2.0
webui: '[PROTO:ssl]://[HOST]:[PORT:8181]'
