name: Example
version: 8.0.3
slug: example
description: Example add-on by Community Home Assistant Add-ons
url: https://github.com/hassio-addons/addon-example
codenotary: codenotary@frenck.dev
init: false
arch:
- aarch64
- amd64
- armv7
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.io/hassio-addons/example/{arch}
