name: Whisparr
version: 0.1.0
slug: whisparr
description: Whisparr is an adult video collection manager for Usenet and BitTorrent
  users
url: https://github.com/hassio-addons/addon-whisparr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:6969]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  6969/tcp: 6969
image: ghcr.io/hassio-addons/whisparr/{arch}
