name: EMQX
version: 0.6.0
slug: emqx
description: The most scalable open-source MQTT broker for IoT. An alternative for
  the Mosquitto add-on
url: https://github.com/hassio-addons/addon-emqx
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 18083
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: EMQX
arch:
- aarch64
- amd64
map:
- ssl
options:
  env_vars: []
host_network: true
schema:
  env_vars:
  - name: match(^EMQX_([A-Z0-9_])+$)
    value: str
image: ghcr.io/hassio-addons/emqx/{arch}
