name: motionEye
version: 0.20.0
slug: motioneye
description: Simple, elegant and feature-rich CCTV/NVR for your cameras
url: https://github.com/hassio-addons/addon-motioneye
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:cctv
homeassistant: 0.92.0b2
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
discovery:
- motioneye
host_network: true
apparmor: false
video: true
privileged:
- DAC_READ_SEARCH
- SYS_ADMIN
map:
- media:rw
- share:rw
- ssl
options:
  motion_webcontrol: false
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  action_buttons: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  motion_webcontrol: bool
  ssl: bool
  certfile: str
  keyfile: str
  action_buttons:
  - type: list(lock|unlock|light_on|light_off|alarm_on|alarm_off|up|right|down|left|zoom_in|zoom_out|preset1|preset2|preset3|preset4|preset5|preset6|preset7|preset8|preset9)?
    camera: int?
    command: str?
image: ghcr.io/hassio-addons/motioneye/{arch}
