name: JupyterLab
version: 0.15.1
slug: jupyterlablite
description: Create documents containing live code, equations, visualizations, and
  explanatory text
url: https://github.com/hassio-addons/addon-jupyterlab
codenotary: codenotary@frenck.dev
ingress: true
panel_icon: mdi:flask-outline
arch:
- aarch64
- amd64
homeassistant_api: true
init: false
map:
- config:rw
- share:rw
options:
  github_access_token: ''
  system_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  github_access_token: password
  system_packages:
  - str
  init_commands:
  - str
image: ghcr.io/hassio-addons/jupyterlab/{arch}
