name: Readarr
version: 0.1.0
slug: readarr
description: Book Manager and Automation (Sonarr for Ebooks)
url: https://github.com/hassio-addons/addon-readarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8787]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8787/tcp: 8787
image: ghcr.io/hassio-addons/readarr/{arch}
