name: Prowlarr
version: 0.6.0
slug: prowlarr
description: Indexer manager/proxy built on the popular arr stack to integrate with
  your various PVR apps
url: https://github.com/hassio-addons/addon-prowlarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:9696]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  9696/tcp: 9696
image: ghcr.io/hassio-addons/prowlarr/{arch}
