arch:
- aarch64
- amd64
description: Modern GPS Tracking Platform
host_network: true
image: ghcr.io/hassio-addons/traccar/{arch}
ingress: true
ingress_port: 0
init: false
map:
- config:rw
- ssl
name: Traccar
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
panel_icon: mdi:car-connected
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
services:
- mysql:want
slug: traccar
startup: services
url: https://github.com/hassio-addons/addon-traccar
version: 0.15.0
