name: Traccar
version: 0.25.0
slug: traccar
description: Modern GPS Tracking Platform
url: https://github.com/hassio-addons/addon-traccar
webui: '[PROTO:ssl]://[HOST]:[PORT:80]'
codenotary: codenotary@frenck.dev
panel_icon: mdi:car-connected
startup: services
arch:
- aarch64
- amd64
init: false
host_network: true
ports:
  80/tcp: 8082
ports_description:
  80/tcp: Web interface
map:
- addon_config:rw
- homeassistant_config:rw
- ssl
services:
- mysql:want
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
image: ghcr.io/hassio-addons/traccar/{arch}
