name: Bookstack
version: 2.0.5
slug: bookstack
description: Simple & Free Wiki Software
url: https://github.com/hassio-addons/addon-bookstack
codenotary: codenotary@frenck.dev
webui: '[PROTO:ssl]://[HOST]:[PORT:80]'
init: false
arch:
- aarch64
- amd64
- armv7
services:
- mysql:want
map:
- ssl
ports:
  80/tcp: 2665
ports_description:
  80/tcp: Web interface
options:
  envvars: []
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  remote_mysql_host: str?
  remote_mysql_database: str?
  remote_mysql_username: str?
  remote_mysql_password: password?
  remote_mysql_port: int?
  show_appkey: bool?
  appkey: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  envvars:
  - name: str
    value: str
image: ghcr.io/hassio-addons/bookstack/{arch}
