name: FTP
version: 5.0.2
slug: ftp
description: A secure and fast FTP server for Home Assistant
url: https://github.com/hassio-addons/addon-ftp
codenotary: codenotary@frenck.dev
startup: services
arch:
- aarch64
- amd64
- armv7
init: false
host_network: true
privileged:
- SYS_ADMIN
apparmor: false
map:
- addons:rw
- backup:rw
- config:rw
- media:rw
- share:rw
- ssl:rw
options:
  port: 21
  data_port: 20
  banner: Welcome to the Hass.io FTP service.
  pasv: true
  pasv_min_port: 30000
  pasv_max_port: 30010
  pasv_address: ''
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  implicit_ssl: false
  max_clients: 5
  users:
  - username: hassio
    password: changeme
    allow_chmod: false
    allow_download: false
    allow_upload: false
    allow_dirlist: true
    addons: false
    backup: false
    config: false
    media: true
    share: true
    ssl: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  port: port
  data_port: port
  banner: str
  pasv: bool
  pasv_min_port: port
  pasv_max_port: port
  pasv_address: str
  pasv_addr_resolve: bool?
  ssl: bool
  certfile: str
  keyfile: str
  implicit_ssl: bool
  max_clients: int
  users:
  - username: match(^[a-zA-Z0-9\d](?:[a-zA-Z0-9\d]|-(?=[a-zA-Z0-9\d])){0,32}$)
    password: password
    allow_chmod: bool
    allow_download: bool
    allow_upload: bool
    allow_dirlist: bool
    addons: bool
    backup: bool
    config: bool
    media: bool
    share: bool
    ssl: bool
  i_like_to_be_pwned: bool?
image: ghcr.io/hassio-addons/ftp/{arch}
