name: Grafana
version: 10.0.0
slug: grafana
description: The open platform for beautiful analytics and monitoring
url: https://github.com/hassio-addons/addon-grafana
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 1337
ingress_stream: true
init: false
panel_icon: mdi:chart-timeline
panel_title: Grafana
arch:
- aarch64
- amd64
- armv7
map:
- homeassistant_config
- share
- ssl
options:
  plugins: []
  custom_plugins: []
  env_vars: []
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  80/tcp: null
ports_description:
  80/tcp: Not required for Ingress
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  plugins:
  - str
  custom_plugins:
  - name: str
    url: str
    unsigned: bool?
  certfile: str
  keyfile: str
  ssl: bool
  grafana_ingress_user: str?
  env_vars:
  - name: match(^GF_([A-Z0-9_])+$)
    value: str
image: ghcr.io/hassio-addons/grafana/{arch}
