arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Protect your privacy and access Home Assistant via Tor
image: ghcr.io/hassio-addons/tor/{arch}
init: false
map:
- ssl:rw
name: Tor
options:
  client_names: []
  hidden_services: true
  ports:
  - '8123'
  - 8123:80
  socks: false
  stealth: false
ports:
  9050/tcp: 9050
ports_description:
  9050/tcp: Tor SOCKS proxy port
schema:
  client_names:
  - match(^[A-Za-z0-9+-_]{1,16}$)
  hidden_services: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ports:
  - match(^(.*:)?(?:[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?$)
  socks: bool
  stealth: bool
slug: tor
startup: services
url: https://github.com/hassio-addons/addon-tor
version: 4.1.0
