name: Tor
version: 5.0.1
slug: tor
description: Protect your privacy and access Home Assistant via Tor
url: https://github.com/hassio-addons/addon-tor
codenotary: codenotary@frenck.dev
startup: services
arch:
- aarch64
- amd64
- armv7
init: false
ports:
  9050/tcp: 9050
ports_description:
  9050/tcp: Tor SOCKS proxy port
map:
- ssl:rw
options:
  socks: false
  hidden_services: true
  stealth: false
  client_names: []
  ports:
  - '8123'
  - 8123:80
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  socks: bool
  hidden_services: bool
  stealth: bool
  client_names:
  - match(^[A-Za-z0-9+-_]{1,16}$)
  ports:
  - match(^(.*:)?(?:[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?$)
image: ghcr.io/hassio-addons/tor/{arch}
