name: Grocy
version: 0.21.0
slug: grocy
description: ERP beyond your fridge! A groceries & household management solution for
  your home
url: https://github.com/hassio-addons/addon-grocy
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
init: false
panel_icon: mdi:cart
panel_admin: false
arch:
- aarch64
- amd64
- armv7
map:
- ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  culture: en
  currency: USD
  entry_page: stock
  features:
    batteries: true
    calendar: true
    chores: true
    equipment: true
    recipes: true
    shoppinglist: true
    stock: true
    tasks: true
  tweaks:
    chores_assignment: true
    multiple_shopping_lists: true
    stock_best_before_date_tracking: true
    stock_location_tracking: true
    stock_price_tracking: true
    stock_product_freezing: true
    stock_product_opened_tracking: true
    stock_count_opened_products_against_minimum_stock_amount: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  grocy_ingress_user: ''
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  culture: list(ca|cs|da|de|el_GR|en|en_GB|es|et|fi|fr|he_IL|hu|it|ja|ko_KR|lt|nl|no|pl|pt_BR|pt_PT|ro|ru|sk_SK|sl|sv_SE|ta|tr|uk|zh_CN|zh_TW)
  currency: match(^[A-Z]{3}$)
  entry_page: list(stock|shoppinglist|recipes|chores|tasks|batteries|equipment|calendar|mealplan)
  features:
    batteries: bool
    calendar: bool
    chores: bool
    equipment: bool
    recipes: bool
    shoppinglist: bool
    stock: bool
    tasks: bool
  tweaks:
    calendar_first_day_of_week: int(0,6)?
    chores_assignment: bool
    meal_plan_first_day_of_week: int(0,6)?
    multiple_shopping_lists: bool
    stock_best_before_date_tracking: bool
    stock_location_tracking: bool
    stock_price_tracking: bool
    stock_product_freezing: bool
    stock_product_opened_tracking: bool
    stock_count_opened_products_against_minimum_stock_amount: bool
  ssl: bool
  certfile: str
  keyfile: str
  grocy_ingress_user: str
image: ghcr.io/hassio-addons/grocy/{arch}
