name: AdGuard Home
version: 5.1.0
slug: adguard
description: Network-wide ads & trackers blocking DNS server
url: https://github.com/hassio-addons/addon-adguard-home
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:shield-check
startup: services
homeassistant: 0.113.2
arch:
- aarch64
- amd64
- armv7
init: false
ports:
  53/udp: 53
  80/tcp: null
ports_description:
  53/udp: DNS server port
  80/tcp: Web interface (Not required for Ingress)
discovery:
- adguard
auth_api: true
host_network: true
hassio_api: true
hassio_role: manager
map:
- ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
backup_exclude:
- '*/adguard/data/querylog.*'
image: ghcr.io/hassio-addons/adguard/{arch}
