arch:
- aarch64
- amd64
- armhf
- armv7
- i386
auth_api: true
backup_exclude:
- '*/adguard/data/querylog.*'
codenotary: codenotary@frenck.dev
description: Network-wide ads & trackers blocking DNS server
discovery:
- adguard
hassio_api: true
hassio_role: manager
homeassistant: 0.113.2
host_network: true
image: ghcr.io/hassio-addons/adguard/{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
- ssl
name: AdGuard Home
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
panel_icon: mdi:shield-check
ports:
  53/udp: 53
  80/tcp: null
ports_description:
  53/udp: DNS server port
  80/tcp: Web interface (Not required for Ingress)
schema:
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: adguard
startup: services
url: https://github.com/hassio-addons/addon-adguard-home
version: 4.8.0
