arch:
- aarch64
- amd64
codenotary: codenotary@frenck.dev
description: Fully featured Visual Studio Code (VSCode) experience integrated in the
  Home Assistant frontend.
hassio_api: true
hassio_role: manager
homeassistant_api: true
image: ghcr.io/hassio-addons/vscode/{arch}
ingress: true
ingress_port: 1337
ingress_stream: true
init: false
map:
- config:rw
- ssl:rw
- addons:rw
- media:rw
- share:rw
- backup:rw
name: Studio Code Server
options:
  init_commands: []
  packages: []
panel_icon: mdi:microsoft-visual-studio-code
schema:
  config_path: str?
  init_commands:
  - str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  packages:
  - str
services:
- mysql:want
- mqtt:want
slug: vscode
startup: services
uart: true
url: https://github.com/hassio-addons/addon-vscode
version: 5.5.2
