arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: A web interface for the official MariaDB add-on
hassio_api: true
image: ghcr.io/hassio-addons/phpmyadmin/{arch}
ingress: true
ingress_stream: true
init: false
name: phpMyAdmin
panel_icon: mdi:database
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
services:
- mysql:need
slug: phpmyadmin
url: https://github.com/hassio-addons/addon-phpmyadmin
version: 0.8.3
