arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Centrally manage all your Sonoff-Tasmota devices
image: ghcr.io/hassio-addons/tasmoadmin/{arch}
init: false
map:
- ssl
name: TasmoAdmin
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
ports:
  9541/tcp: 9541
ports_description:
  9541/tcp: TasmoAdmin web interface
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: sonweb
startup: system
url: https://github.com/hassio-addons/addon-tasmoadmin
version: 0.23.0
webui: '[PROTO:ssl]://[HOST]:[PORT:9541]'
