arch:
- aarch64
- amd64
- armhf
- armv7
- i386
description: Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
homeassistant_api: true
image: ghcr.io/hassio-addons/appdaemon/{arch}
init: false
map:
- config:rw
- share:rw
- ssl
name: AppDaemon 4
options:
  init_commands: []
  python_packages: []
  system_packages: []
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon
schema:
  init_commands:
  - str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  python_packages:
  - str
  system_packages:
  - str
slug: appdaemon
uart: true
url: https://github.com/hassio-addons/addon-appdaemon
version: 0.7.1
webui: http://[HOST]:[PORT:5050]
