name: AirCast
version: 4.2.1
slug: aircast
description: AirPlay capabilities for your Chromecast devices.
url: https://github.com/hassio-addons/addon-aircast
codenotary: codenotary@frenck.dev
startup: services
init: false
arch:
- aarch64
- amd64
- armv7
hassio_api: true
host_network: true
map:
- addon_config:rw
- homeassistant_config:rw
options:
  latency_rtp: 0
  latency_http: 0
  drift: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  address: str?
  latency_rtp: int
  latency_http: int
  drift: bool
image: ghcr.io/hassio-addons/aircast/{arch}
