arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Fully configurable Z-Wave JS gateway and control panel
discovery:
- zwave_js
image: ghcr.io/hassio-addons/zwave-js-ui/{arch}
ingress: true
ingress_stream: true
init: false
map:
- share:rw
name: Z-Wave JS UI
panel_icon: mdi:z-wave
panel_title: Z-Wave JS
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Z-Wave JS communication
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
services:
- mqtt:want
slug: zwavejs2mqtt
startup: system
uart: true
udev: true
url: https://github.com/hassio-addons/addon-zwave-js-ui
version: 1.6.0
watchdog: http://[HOST]:[PORT:8099]/health/zwave
