name: Z-Wave JS UI
version: 3.6.0
slug: zwavejs2mqtt
description: Fully configurable Z-Wave JS gateway and control panel
url: https://github.com/hassio-addons/addon-zwave-js-ui
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
panel_title: Z-Wave JS
panel_icon: mdi:z-wave
startup: system
init: false
timeout: 30
arch:
- aarch64
- amd64
- armv7
discovery:
- zwave_js
services:
- mqtt:want
uart: true
udev: true
map:
- share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Z-Wave JS communication
image: ghcr.io/hassio-addons/zwave-js-ui/{arch}
