name: ZeroTier One
version: 0.18.0
slug: zerotier
description: Radically simplify your network with a virtual networking layer that
  works the same everywhere
url: https://github.com/hassio-addons/addon-zerotier
codenotary: codenotary@frenck.dev
startup: services
init: false
arch:
- aarch64
- amd64
- armv7
ports:
  9993/tcp: 9993
ports_description:
  9993/tcp: ZeroTier's primary port
host_network: true
privileged:
- NET_ADMIN
- SYS_ADMIN
devices:
- /dev/net/tun
map:
- ssl:rw
options:
  networks: []
  api_auth_token: ''
schema:
  networks:
  - match(^!secret [a-zA-Z0-9_\-]+$|[0-9a-z]{16})
  api_auth_token: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/hassio-addons/zerotier/{arch}
