arch:
- aarch64
- amd64
- armv7
- i386
codenotary: codenotary@frenck.dev
description: AirPlay capabilities for your Sonos (and UPnP) devices.
hassio_api: true
host_network: true
image: ghcr.io/hassio-addons/airsonos/{arch}
init: false
map:
- config:rw
name: AirSonos
options:
  drift: false
  latency_http: 2000
  latency_rtp: 1000
  port: 49152
schema:
  address: str?
  drift: bool
  latency_http: int
  latency_rtp: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  port: port
slug: airsonos
startup: services
url: https://github.com/hassio-addons/addon-airsonos
version: 3.5.1
