name: Spotify Connect
version: 0.13.0
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/hassio-addons/addon-spotify-connect
codenotary: codenotary@frenck.dev
arch:
- aarch64
- amd64
- armv7
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  bitrate: 160
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  username: str?
  password: password?
image: ghcr.io/hassio-addons/spotify/{arch}
