name: UniFi Network Application
version: 3.0.5
slug: unifi
description: Manage your UniFi network using a web browser
url: https://github.com/hassio-addons/addon-unifi
codenotary: codenotary@frenck.dev
webui: https://[HOST]:[PORT:8443]
startup: services
arch:
- aarch64
- amd64
init: false
backup: cold
map:
- backup:rw
ports:
  161/udp: null
  1900/udp: null
  3478/udp: 3478
  5514/udp: 5514
  6789/tcp: 6789
  8080/tcp: 8080
  8443/tcp: 8443
  8843/tcp: 8843
  8880/tcp: 8880
  10001/udp: 10001
ports_description:
  161/udp: Used for SNMP Access
  1900/udp: L2 discoverable port
  3478/udp: Used for STUN
  5514/udp: Used for remote syslog debugging
  6789/tcp: Used for UniFi mobile speed test
  8080/tcp: Used for device and controller communication
  8443/tcp: Used for controller web interface and API
  8843/tcp: Used for HTTPS portal redirection
  8880/tcp: Used for HTTP portal redirection
  10001/udp: Used for device discovery
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  memory_max: int?
  memory_init: int?
image: ghcr.io/hassio-addons/unifi/{arch}
