name: SQLite Web
version: 3.7.1
slug: sqlite-web
description: Explore your SQLite database
url: https://github.com/hassio-addons/addon-sqlite-web/tree/main/README.md
codenotary: codenotary@frenck.dev
ingress: true
advanced: true
init: false
panel_icon: mdi:database
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
map:
- config:rw
- share:rw
schema:
  database: str?
image: ghcr.io/hassio-addons/sqlite-web/{arch}
