name: SQLite Web
version: 6.0.0
slug: sqlite-web
description: Explore your SQLite database
url: https://github.com/hassio-addons/app-sqlite-web/tree/main/README.md
ingress: true
advanced: true
init: false
panel_icon: mdi:database
arch:
- aarch64
- amd64
map:
- homeassistant_config:rw
- share:rw
schema:
  database: str?
image: ghcr.io/hassio-addons/sqlite-web
