name: Uptime Kuma
version: 0.16.0
slug: uptime-kuma
description: It is a self-hosted monitoring tool like "Uptime Robot"
url: https://github.com/hassio-addons/app-uptime-kuma
webui: http://[HOST]:[PORT:3001]
init: false
arch:
- aarch64
- amd64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
- uptime_kuma
image: ghcr.io/hassio-addons/uptime-kuma
